server:
  port: 8888
spring:
  application:
    name: ConfigService
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zebanaourin/BA_microservices_config
          clone-on-start: true
logging:
  pattern:
    console: "%msg%n"